sources:
  - name: source_bronze
    database: pysparkdbt  
    schema: bronze  
    tables:
      - name: trips


  - name: source_silver
    database: pysparkdbt  
    schema: silver  
    tables:
      - name: locations
      - name: vehicles
      - name: payments
      - name: customers
      - name: drivers




